### ISSUE TITLE
Enforcing trailing slash in URL

### ISSUE THREAD

**Issue by sarathms** [ooni/test-lists-ui#23]
There was a suggestion from @bassosimone that we could make the trailing slash (`/`) in the URL input optional in the UI and add it, as part of a normalization step before sending it to the backend.

> I think the correct fix should be something like parsing the URL in JavaScript and normalizing it
I am thinking that that would be a good place to make it canonical including the final `/`

**Comment by hellais** [comment]
Yeah I think we should do this when the user clicks the add button.
