### ISSUE TITLE
Allow updating existing entries

### ISSUE THREAD

**Issue by arky** [ooni/test-lists-ui#4]
Allow users to update an existing entry by selecting and editing them. This is usually the most common task when working with test lists.

**Comment by hellais** [comment]
Can you clarify what you mean exactly by supporting updating an entry by "selecting and editing them"? I think the workflow we imagined was such that we wanted to enforce that there would be a reason for every edit made to a specific URL and hence there is the modal for editing a URL.

**Comment by arky** [comment]
This feature is available in the production. 

Closing this as resolved.
