### ISSUE TITLE
Add copy to the test list UI landing page (prior to login)

### ISSUE THREAD

**Issue by agrabeli** [ooni/test-lists-ui#54]
The test list web platform (https://test-lists.ooni.org/) currently misses copy that can help explain what this platform is, why users should engage with it, etc. Moreover, the "Quick start guide" includes information that is actually only relevant once the user is logged in (and at that point, they can't easily go back to view the steps in the quick start guide).

I therefore propose the following copy for the test list platform **landing page (before login)**:

- [x] Add title: **Test lists submission system** (this might change)
- [x] Add subtitle: **Contribute websites for censorship testing**
- [x] Add the following copy under the subtitle, and before the email slot:

```
Add your email address and click the link sent to your email to log into this platform. We do not store email addresses. 
```

- [x] Delete the "Quick Start Guide"
- [x] Add the following copy on the landing page (where the "Quick Start Guide" used to be):

```
To discover the blocking of websites around the world, tools like [OONI Probe](https://ooni.org/install) rely on certain lists of websites ("[test lists](https://ooni.org/get-involved/contribute-test-lists)"). This platform includes these lists, which you can review and contribute to. 

Help the internet freedom community discover website blocks around the world by contributing websites for testing!
```

**Comment by agrabeli** [comment]
@hellais please review.

**Comment by hellais** [comment]
Yeah this looks good. I made some small edits to the top level comment

**Comment by agrabeli** [comment]
Thanks @majakomel for implementing these changes. <3
