### ISSUE TITLE
Add copy to test list UI platform (selecting a country)

### ISSUE THREAD

**Issue by agrabeli** [ooni/test-lists-ui#55]
This ticket is a follow-up to: https://github.com/ooni/test-lists-ui/issues/54

![test-list-logged-in](https://user-images.githubusercontent.com/8290574/180280198-cb6e8c5c-32ac-4a99-a58e-09d0e9409f91.png)

On the above page, I propose the following changes:

- [ ] Delete the "Quick Start Guide"
- [ ] Add the following copy (where the "Quick Start Guide" used to be):

```
**Important:** Internationally-relevant websites (such as facebook.com) are tested by [OONI Probe](https://ooni.org/install) users globally, and are only meant to be included in the Global test list. 
```

**Comment by agrabeli** [comment]
@hellais please review.

**Comment by hellais** [comment]
LGTM

**Comment by agrabeli** [comment]
Thanks @majakomel for implementing these changes. <3
