### ISSUE TITLE
Change the footer links

### ISSUE THREAD

**Issue by agrabeli** [ooni/test-lists-ui#56]
I propose the following changes to the footer of the test list web platform (https://test-lists.ooni.org/):

- [ ] Replace "Code of Conduct" with "About Test Lists", linking to https://ooni.org/get-involved/contribute-test-lists
- [ ] Replace the Source Code link with https://github.com/ooni/test-lists-ui

I propose these changes because:
* Linking to the Code of Conduct seems a bit irrelevant here (since updating lists is a solitary activity), while the main thing that's important is to link to detailed information about test lists (that can help community members contribute updates)
* Rather than linking to URL prioritization code, it's probably more relevant and important to link to the test list UI code (where contributors can find their pull requests)

**Comment by agrabeli** [comment]
@hellais please review.

**Comment by hellais** [comment]
LGTM

**Comment by agrabeli** [comment]
Thanks @majakomel for implementing these changes. <3
