### ISSUE TITLE
Dropdowns making page unscrollable

### ISSUE THREAD

**Issue by GermaVinsmoke** [ooni/test-lists-ui#60]
When the dropdown is open then the page becomes unscrollable. The only way to make it scrollable is by closing the dropdown.

**Browser - Firefox 103.0**

![image](https://user-images.githubusercontent.com/32815509/181692184-1a7f56f6-1ea1-4019-a638-cec69457fb40.png)

**Comment by majakomel** [comment]
Closing this as it is normal behavior for native elements (see behavior on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select for example). The only way to go around it would be to implement a custom select component, but the effort of doing it is not justifiable at the moment.
