### ISSUE TITLE
Add/Edit priority rules is broken

### ISSUE THREAD

**Issue by hellais** [ooni/test-lists-ui#71]
When I access https://test-lists.ooni.org/prioritization/ and attempt to add a new priority rule I get a 401 error with the message: `{"error":"Authentication required"}`.

It's unclear if this is a backend or frontend bug.

Screenshot attached:
![Screenshot 2023-02-07 at 14 25 26](https://user-images.githubusercontent.com/424620/217261404-a8ad7350-6940-462d-8807-96ce797a8f6c.png)

**Comment by majakomel** [comment]
This is fixed in https://github.com/ooni/test-lists-ui/commit/16698ba41aaf21a47e0697fc44bc123c25606846
